spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  #配置阿里巴巴数据源
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/springcloud1?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      dbcp2:
        min-idle: 5
        initial-size: 5
        max-total: 5
        max-wait-millis: 200
server:
  port: 8080
#配置mybatis
mybatis:
  #  config-location: classpath:mybatis/mybatis.xml
  mapper-locations:
    - classpath:mybatis/mappers/**/*.xml
  type-aliases-package: springcloud.entities
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
    cache-enabled: true   #开启二级缓存

---
spring:
  profiles: test
  #配置阿里巴巴数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud2?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
server:
  port: 8081
#配置mybatis
mybatis:
  #  config-location: classpath:mybatis/mybatis.xml
  mapper-locations:
    - classpath:mybatis/mappers/**/*.xml
  type-aliases-package: springcloud.entities
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法
    cache-enabled: true   #开启二级缓存

