spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: cloud-provider-payment
config:
  info: "hello bus"

---
spring:
  profiles: test
  application:
    name: cloud-provider-payment
 
