spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
     name: cloud-dev

server:
  port: 8761  #设置eureka注册中心端口号

eureka:
  client:
    service-url:
           defaultZone: http://localhost:8761/eureka/  #这里不设置也可以因为，初始化的时候springcloud设置的就是这个url

---
spring:
  profiles: test
  application:
    name: cloud-test

server:
  port: 8762  #设置eureka注册中心端口号

eureka:
  client:
    service-url:
           defaultZone: http://localhost:8762/eureka/  #这里不设置也可以因为，初始化的时候springcloud设置的就是这个url

